applications/users/urls.py
from django.conf.urls import url
# para poder importar las imagenes
from django.views.static import serve
from .views import *
# from views import Usuarios
from django.conf import settings

# from django.views.static.
urlpatterns = [
    # url(r'^usuarios', Usuarios.as_view(), name='inicio'),
    # cuidado con esto tiene GRUD de Usuarios
    # url(r'^$', UsuarioVer.as_view(), name='p_inicio'),
    url(r'^nuevo/$', Usuario_crear.as_view(),
        name='pu_nuevo'),
    url(r'^editar/(?P<pk>\d+)$',
        UsuarioEditar.as_view(), name='p_editar'),
    url(r'^eliminar/(?P<pk>\d+)$',
        UsuarioEliminar.as_view(), name='p_eliminar'),
    url(r'^cambio_contrasena$', change_password,
        name='change_password'),
    url(r'^contrasena$', cambio_contrasena,
        name='p_cambio_contrasena'),
    url(r'^(?P<usuario>[^/]+)$', Ver_perfil.as_view(),
        name='p_ver_perfil'),
    url(r'^(?P<usuario>[^/]+)/editar$', Editar_perfil.as_view(),
        name='p_editar_perfil'),
    url(r'^(?P<usuario>[^/]+)/cuenta$', Cuenta_usuario.as_view(),
        name='p_cuenta'),
    url(r'^cambiar_cuenta_usuario/$', Cambiar_cuenta_usuario.as_view(),
        name='p_cambiar_cuenta_usuario'),
    url(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
]

hackactivista/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.conf import settings
from applications.users.views import (change_password, 
                                        registro_usuario_modals, 
                                        Completar_registro_perfil,
                                        Registrarse, Index_principal,
                                        LogOut, userlogin,
                                        activate)
# para cambio de contraseña con redes scciales
from applications.users import views as core_views
from applications.configurations.views import TermsCondition, PrivacyPolice

urlpatterns = [
    # admin
    url(r'^administrador/', admin.site.urls),
    url(r'^$', Index_principal.as_view(), name="index_principal"),
    # politicas y privacidad para pedir correo al memento de auntenticacion con redes sociales.
    url(r'^politicas$', PrivacyPolice.as_view(), name="p_politicas"),
    url(r'^terminos$', TermsCondition.as_view(), name="p_terminos"),
    url(r'quienes-somos', TemplateView.as_view(
        template_name='quienes-somos.html'), name='p_quienes_somos'),
    url(r'proyectos/$', TemplateView.as_view(
        template_name='proyectos.html'), name='p_nuestros_proyectos'),
    path(r'covid19/', include(('applications.covid19.urls', 'app_cuvid19'), 
                    namespace='app_cuvid19')),
    url(r'coronavirus/evolucion-casos-covid-19-peru/$', TemplateView.as_view(
        template_name='casos-covid-19.html'), name='p-casos-covid-19'),

    url(r'team-hackactivistas', TemplateView.as_view(
        template_name='team-hackactivistas.html'), name='p_team_hackactivistas'),

    url(r'pagina-interes', TemplateView.as_view(
        template_name='pagina-interes.html'), name='p_pagina-interes'),

    url(r'proyectos/alerta-minsa', TemplateView.as_view(
        template_name='alerta-minsa.html'), name='p_alerta-minsa'),
    
    url(r'proyectos/bio-covid19', TemplateView.as_view(
        template_name='bio-covid19.html'), name='p_bio-covid19'),

    url(r'proyectos/chat-covid19', TemplateView.as_view(
        template_name='chat-covid19.html'), name='p_chat-covid19'),
        url(r'proyectos/kitchay-coronavida', TemplateView.as_view(
        template_name='kitchay-coronavida.html'), name='p_kitchay-coronavida'),
    # para auntenticacion con redes sociales
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    # para forzar cambio de contraseña despues de haberse autenticado con
    # redes sociales
    url(r'^settings/$', core_views.settings, name='settings'),
    url(r'^settings/password/$', core_views.password, name='password'),
    url(r'^iniciar/$', userlogin, name="iniciar_sesion"),
    url(r'^salir/$', LogOut, name='cerrar_sesion'),
    # para recuperacion de contraseña
    url('^', include('django.contrib.auth.urls')),
    path(r'users/', include(('applications.users.urls', 'app_users'), namespace='app_users')),
    # para activar el correo
    path(r'registrarse/', Registrarse.as_view(), 
        name="registrarse_usuario"),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',activate, name='activate'),
    url(r'^completar_registro_usuario/$', Completar_registro_perfil.as_view(),
        name='completar_registro_perfil_usuario'),

    # editor django-markdown-editor
    url('martor/', include('martor.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.views import serve as static_serve
    staticpatterns = static(settings.STATIC_URL, view=static_serve)
    mediapatterns = static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = staticpatterns + mediapatterns + urlpatterns

applications/users/models.py
from django.db import models
from django.utils import timezone
from django.utils.http import urlquote
from django.utils.translation import ugettext_lazy as _
from django.core.mail import send_mail
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.contrib.auth.models import Group
from django.shortcuts import get_object_or_404

from django.conf import settings
from django.core.mail import send_mail

from django.core.exceptions import ValidationError
class CustomUserManager(BaseUserManager):

    # aqui falta agregar correo en caso de registrar correo por redes sociales
    # de momento solo estara disponible con usuario
    def _create_user(self, usuario, email, password,
                     is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        email = self.normalize_email(email)
        now = timezone.now()
        if not email:
            raise ValueError('The given email must be set')
        user, created = self.get_or_create(email=email)
        if created: 
            user.set_password(password)
            user.usuario=usuario
            user.last_login=now
            user.date_joined=now
            user.is_staff=is_staff
            user.is_active = True
            user.is_superuser = is_superuser
            user.save()
            grupo, created = Group.objects.get_or_create(name='Emprendedor')
            # get_or_create() didn't have to create an object.
            user.groups.add(grupo)
            Perfil_usuario.objects.create(usuario=user)
        else:
            # user.set_password(password)
            # user.usuario = usuario
            # user.is_staff = is_staff
            # user.is_active = True
            user.last_login = now
            # user.date_joined = now
            # user.is_superuser = is_superuser
            user.save()
        return user



    def create_user(self, usuario, email, password=None, **extra_fields):
        return self._create_user(usuario, email, password, False, False,
                                 **extra_fields)

    def create_superuser(self, usuario, email, password, **extra_fields):
        return self._create_user(usuario, email, password, True, True,
                                 **extra_fields)


class Usuario(AbstractBaseUser, PermissionsMixin):

    usuario = models.CharField(_('Usuario'), max_length=60, unique=True)
    email = models.EmailField(null=True, unique=True)
    is_staff = models.BooleanField(_('staff status'), default=False,
                                   help_text=_('Designates whether the user can log into this admin '
                                               'site.'))
    # importante porque activaremos con confirmacion de correo de registro
    is_active = models.BooleanField(_('active'), default=False,
                                    help_text=_('Designates whether this user should be treated as '
                                                'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    objects = CustomUserManager()
    # cuidado solo el inicio de sesion esta configurado con correo:
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['usuario']
    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('Usuarios')

    def __str__(self):
        return "%s - %s" %  (self.usuario, self.email)

    def get_absolute_url(self):
        return "/users/%s/" % urlquote(self.usuario)

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.usuario)    
        return (full_name.strip()) or u''

    def get_short_name(self):
        "Returns the short name for the user."
        return (self.usuario) or u''

    def email_user(self, subject, message, from_email=None):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.usuario])


class Perfil_usuario(models.Model):
    """docstring for Perfil_usuario"""
    select_pais = (
        ('Peru', 'Perú'),
        ('Bolivia', 'Bolivia'),
        ('Chile', 'Chile'),
        ('Ecuador', 'Ecuador'),
        ('Colombia', 'Colombia'),
        ('Argentina', 'Argentina'),
        ('Brasil', 'Brasil'),
        ('Mexico', 'Mexico'),
        ('Otros', 'Otros')
    )

    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    # dni = models.CharField(max_length=8, unique=True, null=True)
    nombres = models.CharField(max_length=120, null=True)
    apellidos = models.CharField(max_length=80, null=True)
    fecha_nacimiento = models.DateField(null=True,blank=True)
    sexo = models.CharField(choices=(('M', 'Masculino'), ('F', 'Femenino')),
                            max_length=20, null=True, blank=True)
    foto = models.ImageField(upload_to='fotos_usuarios',
                             default='fotos_usuarios/avatar.png', blank=True)
    celular = models.DecimalField(
        max_length=12, max_digits=12, decimal_places=0, null=True)
    codigo_pais = models.CharField(max_length=50, null=True, blank=True)
    pais = models.CharField(max_length=50, choices=select_pais, default='Peru', blank=True, null=True)
    ciudad = models.CharField(max_length=80, null=True)
    ocupacion = models.CharField(max_length=120, null=True, blank=True)
    profesion = models.CharField(max_length=120, null=True, blank=True)
    biografia = models.TextField(null=True, blank=True)
    sitio_web = models.URLField(null=True, blank=True)
    facebook= models.URLField(null=True, blank=True)
    twitter = models.URLField(null=True, blank=True)
    edad = models.IntegerField(null=True, blank=True)
    empresa = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return "%s - %s - %s" %  (self.nombres, self.apellidos, self.usuario.usuario ) or u''

    class Meta:
        verbose_name_plural = _('Perfil Usuarios')
        verbose_name = _('Perfil Usuario')

applications/users/templates/users/login.html
{% extends "base-not-footer.html" %}
{% block title %} Hackactivistas | Inicio de Sesión{% endblock title %}
{% load static %}
{% block contenido %}

<div class="container mt-5">
  {% if not request.user.is_authenticated %}
  <br>
  <div class="row justify-content-center ">

       <form action=".?next={{ redirect_to }}" method="post" class="form-signin">{% csrf_token %}
      {% if form.errors %}
              <div class="alert alert-danger" role="alert">
                  {{ form.errors }}
              </div>
        {% endif %}
        <div class="card col-md-12 px-5">

            <div class="card-body">

           
            <div class="text-center mt-4">
                <h3 class="dark-grey-text mb-4">
                    <strong>Iniciar sesión</strong>
                </h3>
            </div>

            <!--Body-->

            <div class="form-group">
                <label for="Form-email1">Correo:</label>
                <input type="email" id="Form-email" name="email" class="form-control  mb-3">
            </div>

            <div class="form-group ">
                <label for="Form-pass1 mx-0">Contraseña:</label>
                <input type="password" id="Form-pass1" name="password" class="form-control">
                <a href="/password_reset" class="blue-text  "><p class="font-small blue-text d-flex justify-content-end">Olvidastes tu Contraseña?</p></a>
            </div>

            <div class="text-center mb-3">
                <button type="submit" class="btn-hack-green "> <i class="fas fa-sign-in-alt"></i> Iniciar</button>
            </div>


        </div>

        <!--Footer-->
        <div class=" text-center pt-2 mb-1">
            <p class="font-small grey-text  ">No eres miembro? <a href="/registrarse" class="blue-text ml-1"> Registrate</a></p>
        </div>

    </div>
</form> 
  </div>
    {% else %}
    <p>Ya inicio su sesión <a href=" {% url 'cerrar_sesion' %} ">Cerrar</a></p>
    {% endif %}
</div>
{% endblock contenido %}

applications/users/templates/users/register-user.html
{% extends "base-not-footer.html" %}
{% block title %}Hackactivistas | Registro de Cuenta{% endblock title %}
{% load static %}
{% block contenido %}
    <div class="container">
    <br>
    {% if not request.user.is_authenticated %}  
      <div class="row justify-content-center ">
      <form role="form" method="POST" enctype="multipart/form-data">{% csrf_token %}
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {{ form.errors }}
            </div>
        {% endif %}

        <div class=" card col-md-12 mt-5">

        <div class="card-body ">

           
            <div class="text-center">
                <h3 class="dark-grey-text mb-4"> <strong>Registrarse</strong></h3>
            </div>
            <!--Body-->
           <div class="form-group  ">
                {{form.usuario}}
                {{form.usuario.label_tag}}
            </div>
            <div class="form-group ">
                 {{form.email}}
                  {{form.email.label_tag}}
            </div>
            <div class="form-group ">
                 <input type="text" name="celular" class="form-control" maxlength="12" required="" id="id_celular">
                  <label for="id_email" class="">Celular:</label>
            </div>
            <div class="form-grouppb-3">
                 {{form.password}}
                {{form.password.label_tag}}
            </div>
            <div class="text-center mb-3">
                <button type="submit" class="btn-hack-green "> <i class="fas fa-user-plus"></i> Registrarse </button>
            </div>    

        </div>

        <!--Footer-->
        <div class="modal-footer mx-5 pt-3 mb-1">
          <span class="tiene_cuenta">¿Ya tienes una cuenta?<a href=" {% url 'iniciar_sesion' %} "> Iniciar sesión?</a></span>
        </div>

      </form>
      </div>
      {% else %}
        <p>Ya se registró  <a href=" {% url 'cerrar_sesion' %} ">Cerrar</a></p>
      {% endif %}

    </div>

{% endblock contenido %}