applications/covid19/urls.py
from django.conf.urls import url
from .views import *

# from django.views.static.
urlpatterns = [
    url(r'^$', DiagnosisCovid19.as_view(), name='p_diagnosis_covid_19'),
    # url(r'^covid19-img-upload/$', Covid19ImgUpload.as_view(), name='covid19_img_upload')
]

hackactivista/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.conf import settings
from applications.users.views import (change_password, 
                                        registro_usuario_modals, 
                                        Completar_registro_perfil,
                                        Registrarse, Index_principal,
                                        LogOut, userlogin,
                                        activate)
# para cambio de contraseña con redes scciales
from applications.users import views as core_views
from applications.configurations.views import TermsCondition, PrivacyPolice

urlpatterns = [
    # admin
    url(r'^administrador/', admin.site.urls),
    url(r'^$', Index_principal.as_view(), name="index_principal"),
    # politicas y privacidad para pedir correo al memento de auntenticacion con redes sociales.
    url(r'^politicas$', PrivacyPolice.as_view(), name="p_politicas"),
    url(r'^terminos$', TermsCondition.as_view(), name="p_terminos"),
    url(r'quienes-somos', TemplateView.as_view(
        template_name='quienes-somos.html'), name='p_quienes_somos'),
    url(r'proyectos/$', TemplateView.as_view(
        template_name='proyectos.html'), name='p_nuestros_proyectos'),
    path(r'covid19/', include(('applications.covid19.urls', 'app_cuvid19'), 
                    namespace='app_cuvid19')),
    url(r'coronavirus/evolucion-casos-covid-19-peru/$', TemplateView.as_view(
        template_name='casos-covid-19.html'), name='p-casos-covid-19'),

    url(r'team-hackactivistas', TemplateView.as_view(
        template_name='team-hackactivistas.html'), name='p_team_hackactivistas'),

    url(r'pagina-interes', TemplateView.as_view(
        template_name='pagina-interes.html'), name='p_pagina-interes'),

    url(r'proyectos/alerta-minsa', TemplateView.as_view(
        template_name='alerta-minsa.html'), name='p_alerta-minsa'),
    
    url(r'proyectos/bio-covid19', TemplateView.as_view(
        template_name='bio-covid19.html'), name='p_bio-covid19'),

    url(r'proyectos/chat-covid19', TemplateView.as_view(
        template_name='chat-covid19.html'), name='p_chat-covid19'),
        url(r'proyectos/kitchay-coronavida', TemplateView.as_view(
        template_name='kitchay-coronavida.html'), name='p_kitchay-coronavida'),
    # para auntenticacion con redes sociales
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    # para forzar cambio de contraseña despues de haberse autenticado con
    # redes sociales
    url(r'^settings/$', core_views.settings, name='settings'),
    url(r'^settings/password/$', core_views.password, name='password'),
    url(r'^iniciar/$', userlogin, name="iniciar_sesion"),
    url(r'^salir/$', LogOut, name='cerrar_sesion'),
    # para recuperacion de contraseña
    url('^', include('django.contrib.auth.urls')),
    path(r'users/', include(('applications.users.urls', 'app_users'), namespace='app_users')),
    # para activar el correo
    path(r'registrarse/', Registrarse.as_view(), 
        name="registrarse_usuario"),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',activate, name='activate'),
    url(r'^completar_registro_usuario/$', Completar_registro_perfil.as_view(),
        name='completar_registro_perfil_usuario'),

    # editor django-markdown-editor
    url('martor/', include('martor.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.views import serve as static_serve
    staticpatterns = static(settings.STATIC_URL, view=static_serve)
    mediapatterns = static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = staticpatterns + mediapatterns + urlpatterns

templates/base-not-footer.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static from staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
<meta http-equiv=”Pragma” content=”no-cache”>
<meta http-equiv=”Expires” content=”-1″>
<meta http-equiv=”CACHE-CONTROL” content=”NO-CACHE”>
    <title>{% block title %}Hackactivista {% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href=" {% static "img/favicon/icon.png" %}"/>
    <meta name="description" content="{% block description %}Somos un movimiento voluntario de activistas de la información al servicio de una sociedad abierta{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--<body class="hold-transition skin-blue sidebar-mini" oncontextmenu="return false" > -->
    <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet">
    <!-- Bootstrap core CSS -->

    <!-- icon font -->
    <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet">
          <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">

    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static "css/mdb.min.css" %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <!-- Datatable -->
    <link href="{% static "css/jquery.dataTables.css" %}" rel="stylesheet">
    <!-- Para seleccion de AUTOCOMPLETE busquedas-->
    <link href=" {% static "css/select2.min.css" %}" rel="stylesheet"/>

    <link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />

    <style>
        .no-js #loader {
            display: none;
        }

        .js #loader {
            display: block;
            position: absolute;
            left: 100px;
            top: 0;
        }

        .se-pre-con {
            position: fixed;
            left: 0px;
            top: 0px;
            width: 100%;
            height: 100%;
            z-index: 9999;
            opacity: 0.9;
            background: url({% static 'preloader/Preloader_1.gif'%}) center no-repeat #fff;
        }
    </style>
    {% block css %} {% endblock %}

</head>

<body>
{% include 'messages.html' %}
{% include 'header.html' %}
<!--<div class="se-pre-con"></div>
<div class="site-content"></div>-->
{% block contenido %}
{% endblock %}
<!-- Div para linkear archivo vuejs, las vistas solo se activan cuando coinciden con las rutas definidas en el archivo App.js -->
<script type="text/javascript">window.csrf_token = "{% csrf_token %}"</script>
{#<div id="vueapp"></div>#}

<!-- JQuery -->
<script type="text/javascript" src="{% static "js/jquery-3.2.1.min.js" %} "></script>
<script src="{% static "js/jquery.js" %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src=" {% static "js/popper.min.js" %} "></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static "js/mdb.min.js" %}"></script>
<!-- Datatable -->
<script type="text/javascript" src="{% static "js/jquery.dataTables.js" %}"></script>

<!-- all Script -->
<script type="text/javascript" src="{% static "js/scripts.js" %}"></script>
<!-- Jquery validate -->
<script type="text/javascript" src="{% static "js/jquery.validate.js" %}"></script>
<!-- para buscadores, autocomplete -->
<script src="{% static "js/select2.min.js" %}"></script>
<script src="{% static "js/sweetalert2.all.min.js" %}"></script>

<script src="{% static "js/build.min.js" %}"></script>
<script src="{% static "js/moment.min.js" %}"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twbs-pagination/1.4.1/jquery.twbsPagination.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>

<!--<script>
    $(window).on('load', function () {
        // Animate loader off screen
        $(".site-content").show();
        $(".se-pre-con").fadeOut();
    });
</script>-->
{% block js %}
{% endblock %}
<!-- Load Facebook SDK for JavaScript -->
    <div id="fb-root"></div>
    <script>
        window.fbAsyncInit = function() {
          FB.init({
            xfbml            : true,
            version          : 'v6.0'
          });
        };

        (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/es_LA/sdk/xfbml.customerchat.js';
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    </script>

      <!-- Your customer chat code -->
    <div class="fb-customerchat"
        attribution=setup_tool
        page_id="101423784830598"
        theme_color="#4563ff"
        logged_in_greeting="Hola, ¡estoy listo para ayudarte!"
        logged_out_greeting="Hola, ¡estoy listo para ayudarte!">
  </div>
</body>

</html>

templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static from staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta http-equiv=”Pragma” content=”no-cache”>
    <meta http-equiv=”Expires” content=”-1″>
    <meta http-equiv=”CACHE-CONTROL” content=”NO-CACHE”>
    <title>{% block title %}Hackactivistas {% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href=" {% static "img/favicon/icon.png" %}"/>
    <meta name="description" content="{% block description %}Somos un movimiento voluntario de activistas de la información al servicio de una sociedad abierta{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--<body class="hold-transition skin-blue sidebar-mini" oncontextmenu="return false" > -->
    <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet">
    <!-- Bootstrap core CSS -->

    <!-- icon font -->
    <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet">
          <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">

    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static "css/mdb.min.css" %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <!-- jquery-->
    <script type="text/javascript" src="{% static "js/jquery-3.2.1.min.js" %} "></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
    <!-- Datatable -->
    <link href="{% static "css/jquery.dataTables.css" %}" rel="stylesheet">
    <!-- Para seleccion de AUTOCOMPLETE busquedas-->
    <link href=" {% static "css/select2.min.css" %}" rel="stylesheet"/>
    <link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />

    <style>
        .no-js #loader {
            display: none;
        }

        .js #loader {
            display: block;
            position: absolute;
            left: 100px;
            top: 0;
        }

        .se-pre-con {
            position: fixed;
            left: 0px;
            top: 0px;
            width: 100%;
            height: 100%;
            z-index: 9999;
            opacity: 0.9;
            background: url({% static 'preloader/Preloader_1.gif'%}) center no-repeat #fff;
        }
    </style>
    {% block css %} {% endblock %}

</head>

<body>
{% include 'messages.html' %}
{% include 'header.html' %}
<!--<div class="se-pre-con"></div>
<div class="site-content"></div>-->
{% block contenido %}
{% endblock %}

{% block js %}
{% endblock %}

</body>

{% include "footer.html" %}
</html>

templates/bio-covid19.html
{% extends "base.html" %}
{% block title %}Hackactivistas | BioCovid19{% endblock title %}
{% load static %}
{% block contenido %}
<div class="container-fluid pt-6">
	<div class="container">
		<div class="row mt-1 mb-4">
			<div class="col-md-6 ">
                <div class="col-md-12 mb-4">
                    
                    <h1 class="title title_35"> Bio<span class="rs_azul">COVID19 </span></h1>
                    <h4>Potenciales inhibidores moleculares de la proteasa de la SARS-CoV-2.</h4>
                </div>
       
                <div class="col-md-12">
                    <p>Hoy en día, no existe una cura ni tratamiento, en ese sentido, se han desarrollado una serie de
                        investigaciones para determinar blancos terapéuticos que actualmente van cursando ensayos
                        clínicos.
                    </p>
                    <p>A partir de lo reportado en la literatura para los fármacos más eficaces contra el SARS-CoV-2 se
                        eligieron la bixina (carotenoide producido de manera natural a partir del achiote) y cloroquina
                        (fármacos inhibidores más eficaces contra el virus). <br> Adicionalmente, se ha sugerido sobre los posibles efectos de la curcumina contra
                        microorganismos patógenos como bacterias, hongos y virus.</p>
                        
                    <p> Según la literatura, la curcumina tiene efectos antivirales sobre virus muy virulentos como el
                        VIH, HTLV-1, HBV, HCV, HPV, HSV, JEV, influenza y Coxsackievirus.
                        La curcumina tiene varias ventajas como antiviral natural, además de ser considerada segura,
                        no tóxica, rentable y fácilmente disponible, es también una molécula altamente pleiotrópica
                        con actividades antiinflamatorias, antioxidantes, quimiopreventivas, quimiosensibilización y
                        radiosensibilización.   </p>
                       
               
                
             
                </div>
            </div>
            
            <div class="col-md-6 mt-2">
                <img class=" img-fluid "  src="{% static "img/inhidores_1.jpg" %}" alt="Potenciales inhibidores moleculares de la proteasa de la SARS-CoV-2.">
            </div>
		</div>
	</div>
</div>
  
{% endblock contenido %}

templates/footer.html
<!-- Site footer -->
    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6 div-footer">
            <h6 class="font-primary">HackActivistas</h6>
            <p class="font-k">Somos un movimiento voluntario de activistas de la información al servicio de una sociedad abierta, nuestra base de fundamenta en la transparencia y colaboración a partir de la integración cultural.</p>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6 class="font-primary">Categorías</h6>
            <ul class="footer-links">
              <li><a href="#" class="font-k">Proyectos</a></li>
              <li><a href="#" class="font-k">Eventos</a></li>
              <li><a href="#" class="font-k">Retos</a></li>
              <li><a href="#" class="font-k">Cursos</a></li>
            </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6 class="font-primary">Enlaces</h6>
            <ul class="footer-links">
              <li><a href="#" class="font-k">¿Quiénes somos?</a></li>
              <li><a href="#" class="font-k">Nuestros proyectos</a></li>
              <li><a href="/team-hackactivistas" class="font-k">Nuestros Hackactivistas</a></li>
              <li><a href="#" class="font-k">Contáctanos</a></li>
            </ul>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text font-k">Copyright &copy; 2020 derechos reservados
         <a href="#">Hackactivistas</a>.
            </p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="https://www.facebook.com/hackactivistas" target="_black"><i class="fab fa-facebook-f"></i></a></li>
               <li><a class="twitter" href="https://github.com/Hackactivistas" target="_black"><i class="fab fa-github"></i></a></li>
              <!--<li><a class="dribbble" href="#"><i class="fab fa-dribbble"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fab fa-linkedin"></i></a></li>    -->
            </ul>
          </div>
        </div>
      </div>
</footer>

templates/header.html
<!--Modal: Login / Register Form-->             
<nav class="menu ">              
      <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">               
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
              <!-- logo -->
    <div class="pl-4 pr-3 pt-3">
           <!-- logo -->
      <a title="Logo hackcactivista" class="font-primary c-b logo-index" href="/"><span>Hackactivistas</span></a>
    </div>

      </div>

      <div class="collapse menu-collapse m-0 p-0" id="menu">
          <ul class="menu-nav idx">
              <li class="dpgable">
                <a href="/quienes-somos" class="size14 color-grey f-ms">¿Quiénes somos?</a>
              </li>
              <li class="dpgable">
              <a href="/proyectos" class=" size14 color-grey f-ms">Nuestros proyectos</a>
            </li>
            <li class="#"><a href="/team-hackactivistas" class="size14 color-grey f-ms">Nuestros Hackactivistas</a>
            </li>  
            <li class=""><a href="/pagina-interes" class="size14 color-grey f-ms">Páginas de interés</a>
            </li>
            <li class=""><a href="/coronavirus/evolucion-casos-covid-19-peru/" class="size14 color-grey f-ms">Evolución de COVID-19</a>
            </li> 
            <li class=""><a href=" {% url 'app_cuvid19:p_diagnosis_covid_19' %} " class="size14 color-grey f-ms">Diagnóstico de COVID-19</a>
            </li> 
            <!--
            <li class=""><a href="#" class="size14 color-grey f-ms">Retos</a>
            </li>       
            <li class=""><a href="#" class="size14 color-grey f-ms">Contáctanos </a>
            </li>   --> 

          </ul> 
          <div class="btn-salir">
            {% if not request.user.is_authenticated %}
            <a href="/iniciar">
             <button class="signup-btn"> <i class="fas fa-user-circle"></i>&nbsp; Iniciar sesión</button>
            </a>
            {% else %}
            <div class="getout-btn">  <span class="ver_mas smalll">Bienvenido: <strong>{{request.user.usuario}}</strong></span>&nbsp;<a href=" {% url 'cerrar_sesion' %} "> <span class="smalll"> Salir</span></a></div>
             
              
              {% endif %}
          </div>


      </div>
    </nav> 

templates/index.html
{% extends "base.html" %}
{% block title %}Hackactivistas Perú{% endblock title %}
{% load static %}
{% block contenido %}
<div class="container-fluid pt-6 cont-index">
	<div class="container   ">
		<div class="row ">
			<div class="col-md-7 ">
				<h1 class="title">Somos <span class="rs_verde_01">Hackactivistas</span></h1>
				<h5 class="pt-2 text-muted">Somos un movimiento voluntario de activistas de la información al servicio de una sociedad abierta, nuestra base se fundamenta en la transparencia y colaboración a partir de la integración cultural. </h5>	
			</div>
			<!--<div class="col-md-6 pt-6">
				<div class="row">
					
					<div class="col-md-12 col-12 pb-3">
						<h1 class="title">Somos <span class="rs_verde_01">Hackactivistas</span></h1>
					</div>
					<div class="col-md-6 col-6">
						<img src="static/img/img3.png" class="img-fluid" alt="">
						<a class="move-left" href="/nuestros-proyectos"><span class="pl-2 font-k c-b size15">Proyectos</span><i class="fas fa-arrow-right c-b size11 pl-2"></i></a>
					</div>
					<div class="col-md-6 col-6">
						<img src="static/img/img1.png" class="img-fluid" alt="">
						<a class="move-left" href="#"><span class="pl-2 font-k c-b size15">Eventos</span><i class="fas fa-arrow-right c-b size11 pl-2"></i></a>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6 col-6">
						<img src="static/img/img4.png" class="img-fluid" alt="">
						<a class="move-left" href="#"><span class="pl-2 font-k c-b size15">Retos</span><i class="fas fa-arrow-right c-b size11 pl-2"></i></a>
					</div>
					<div class="col-md-6 col-6">
						<img src="static/img/img2.png" class="img-fluid" alt="">
						<a class="move-left" href="#"><span class="pl-2 font-k c-b size15">Cursos</span><i class="fas fa-arrow-right c-b size11 pl-2"></i></a>
					</div>
				</div>
			</div>-->
			<div class="col-md-5">
				<img  src="{% static "img/svg/hackactivista_index.svg" %}" class="img-fluid" alt="">
			</div>
		</div>
	</div>
</div>


{% endblock contenido %}

templates/login.html
{% extends "base-not-footer.html" %}
{% block title %}Inicio de Sesión{% endblock title %}
{% load static %}
{% block contenido %}

<div class="container mt-5">
  {% if not request.user.is_authenticated %}
  <br>
  <div class="row justify-content-center ">

       <form action=".?next={{ redirect_to }}" method="post" class="form-signin">{% csrf_token %}
      {% if form.errors %}
              <div class="alert alert-danger" role="alert">
                  {{ form.errors }}
              </div>
        {% endif %}
        <div class="card col-md-12 px-5">

            <div class="card-body">

           
            <div class="text-center mt-4">
                <h3 class="dark-grey-text mb-4">
                    <strong>Iniciar sesión</strong>
                </h3>
            </div>

            <!--Body-->

            <div class="form-group">
                <label for="Form-email1">Correo:</label>
                <input type="email" id="Form-email" name="email" class="form-control  mb-3">
            </div>

            <div class="form-group ">
                <label for="Form-pass1 mx-0">Contraseña:</label>
                <input type="password" id="Form-pass1" name="password" class="form-control">
                <a href="/password_reset" class="blue-text  "><p class="font-small blue-text d-flex justify-content-end">Olvidastes tu Contraseña?</p></a>
            </div>

            <div class="text-center mb-3">
                <button type="submit" class="btn btn-rounded  btn_col primary-color ">Iniciar</button>
            </div>


        </div>

        <!--Footer-->
        <div class=" text-center pt-2 mb-1">
            <p class="font-small grey-text  ">No eres miembro? <a href="/registrarse" class="blue-text ml-1"> Registrate</a></p>
        </div>

    </div>
</form> 
  </div>
    {% else %}
    <p>Ya inicio su sesión <a href=" {% url 'cerrar_sesion' %} ">Cerrar</a></p>
    {% endif %}
</div>
{% endblock contenido %}

templates/messages.html
{% for message in messages %}
<div class="form-row justify-content-center">
  <div class="form-group col-md-6">
    <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
           <span aria-hidden="true">&times;</span>
        </button>
        {{ message }} 
    </div>

  </div>
</div>
{%endfor%}

templates/pagina-interes.html
{% extends "base.html" %}
{% block title %}Hackactivistas | Página de Interés{% endblock title %}
{% load static %}
{% block contenido %}
<div class="container-fluid pt-6">
	<div class="container">
		<div class="row mt-1 mb-4">
			<div class="col-md-6 ">
                <div class="col-md-12 mb-4">
                    <p class="font-primary">1/10</p>
                    <h1 class="title title_35"><span class="rs_naranja"> Plataforma</span> única del Gobierno del Perú - COVID19</h1>
                </div>
       
                <div class="col-md-12">
                    <p class="size15">
                    Aquí encontrarás las medidas, recomendaciones y noticias oficiales del Gobierno Peruano sobre el COVID-19.
                   
                    </p>
                
                    <a href="https://www.gob.pe/coronavirus" target="_blank" class="font-weight-bold"> www.gob.pe/coronavirus</a>
                 <br><br>
                </div>
            </div>
            
            <div class="col-md-6 mt-2">
                <img class="rounded mx-auto d-block " src="static/img/web_coronavirus.png" alt="">
            </div>
		</div>
	</div>
</div>
  
{% endblock contenido %}

templates/politicas.html
{% extends "base.html" %}
{% load static martortags%}

{% block title %} Hackactivistas | Políticas de privacidad {% endblock title %}

{% block contenido %}
	<div class="container-fluid">
	   <div class="row">
	     <main class="col-sm-12 ml-sm-auto col-md-12 mt-5" role="main">
	           <section class="content">
       	    	{% for politic in politics %}
       	    	{% if forloop.first %}
	       	    <div class="form-row center">
			   		<div class="form-group col-md-10 mt-3">
			   			Última Actualización : {{politic.date_create}}
			   			{{politic.content|safe_markdown}}
			   		</div>
			   	</div>
       	    	{% endif %}
       	    	{% endfor %}
	           </section>
	     </main>
	   </div>
	 </div>	
{% endblock contenido %}

templates/proyectos.html
{% extends "base.html" %}
{% block title %}Hackactivista | Nuestros Proyectos{% endblock title %}
{% load static %}
{% block contenido %}
<div class="container-fluid pt-6">
	<div class="container">
		<div class="row mt-2">
			
			<div class="col-md-12 mb-4">
               <h1 class="title "><span class="rs_azul">Proyectos</span>  </h1>
            </div>
            
          <div class="row col-12">
              <div class="col-md-7">
                <div class="col-md-12">
                    <h3 class="sub_title_20">COVIDNetPerú <a href="{% url 'app_cuvid19:p_diagnosis_covid_19' %}" class="icon_enlace"><img src="{% static "img/svg/icon_enlace.svg" %}" alt=""></a></h3>
                    <p class="texto15">Asistencia inteligente para el diagnóstico automatizado de COVID19 por radiografía con Inteligencia Artificial.</p>
                 </div>
                 <div class="col-md-12">
                    <h3 class="sub_title_20">ChatCOVID19 <a href="/proyectos/chat-covid19" class="icon_enlace"><img  src="{% static "img/svg/icon_enlace.svg" %}" alt=""></a></h3>
                    <p class="texto15">Orientación a la ciudadanía para el rápido despistaje vía chatbot.</p>
                 </div>
                 <div class="col-md-12">
                    <h3 class="sub_title_20">Kitchay CoronaVida <a href="/proyectos/kitchay-coronavida" class="icon_enlace"><img  src="{% static "img/svg/icon_enlace.svg" %}" alt=""></a></h3>
                    <p class="texto15">Desarrollo de un kit de salvaguarda para la cuarentena.</p>
                 </div>
              </div>

              <div class="col-md-4">
             
                  <img src="{% static "img/hackactivista-planeta.png" %}" alt="">
              </div>
              
          </div>

        </div>
       
	</div>
</div>
  
{% endblock contenido %}